version: '3'

services:
  gremlin-server:
    build:
      context: ./gremlin-server
      dockerfile: Dockerfile
    ports:
      - "8182:8182"
    volumes:
      - ./.data/:/data/
  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    volumes:
      - ./node-api:/usr/src/app
    ports:
      - "5002:5002"
  reactjs:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"