export const GRAPH = {
  GET_TREE_ROOT: 'GRAPH_GET_TREE_ROOT',
  GET_BY_TYPE: 'GRAPH_GET_BY_TYPE',
  GET_VERTEX_DATA: 'GRAPH_GET_VERTEX_DATA',
  GET_VERTEX_EDGES: 'GRAPH_GET_VERTEX_EDGES',
  UPDATE_COUNT: 'GRAPH_UPDATE_COUNT',
  ERROR: 'GRAPH_ERROR',
}